### ISSUE TITLE
Release binaries on Github

### ISSUE THREAD

**Issue by matthew-james** [rif/spark#10]
Hi,

I noticed that you are hosting the release binaries on Dropbox.  What do you think about [attaching the binaries to the github release](https://help.github.com/articles/distributing-large-binaries/)?  You could also automate it with travis CI [like this](https://docs.travis-ci.com/user/deployment/releases/) so you don't need to do any manual uploading at all.

**Comment by rif** [comment]
Thanks for suggesting it. I attached them to a new release.
