### ISSUE TITLE
Trojan on board?

### ISSUE THREAD

**Issue by Zapperdulchen** [rif/spark#15]
Hi,

I have just downloaded spark_1.7.3_windows_amd64.tar.gz. It seems like there is something wrong with the included spark.exe. My virus scanner was complaining and some 29 out of 69 virus scanners on Virus Total think the same. What is going on here?

Take Care,
Z.

**Comment by rif** [comment]
I compiled the window binary on Linux using cross compilation so a  virus is highly unlikely. I will compile it again with the latest go version and check it before uploading.

**Comment by rif** [comment]
I just generated a new binary and there still are 5 out of 65 virus scanners that detect something suspicious. I believe this is a false positive and it's related to this https://github.com/golang/go/issues/18699. If you are still having doubts feel free to compile it yourself and check it online.
